# Generated by Django 4.2.5 on 2023-12-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='не більше 20 символів', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(help_text='не більше 15 символів', max_length=15)),
                ('message', models.TextField()),
            ],
        ),
    ]
