# Generated by Django 4.2.5 on 2024-01-13 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_month', models.IntegerField()),
                ('price_lesson', models.IntegerField()),
                ('date_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(help_text='оберіть категорію', null=True, on_delete=django.db.models.deletion.CASCADE, to='Web_1.category', verbose_name='категорія курсу')),
                ('kid_age', models.ManyToManyField(help_text='Оберіть вік учня', null=True, to='Web_1.age', verbose_name='Вік учня')),
                ('price', models.ManyToManyField(help_text='Вкажіть вартість', null=True, to='Web_1.price', verbose_name='Вік учня')),
            ],
        ),
    ]
