# Generated by Django 4.2.5 on 2024-02-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_1', '0002_age_category_price_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='kid_age',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.DeleteModel(
            name='Age',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.AddField(
            model_name='course',
            name='kid_age',
            field=models.IntegerField(help_text='Оберіть вік учня', null=True, verbose_name='Вік учня'),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(help_text='Вкажіть вартість', null=True, verbose_name='Вартість'),
        ),
    ]
