# Generated by Django 4.2.5 on 2024-03-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_1', '0003_remove_course_kid_age_remove_course_price_delete_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='date_price',
            field=models.IntegerField(null=True, verbose_name='Дата_ціна'),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=100, null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.TextField(null=True, verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='course',
            name='kid_age',
            field=models.CharField(max_length=50, null=True, verbose_name='Вік учня'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=50, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.CharField(max_length=50, null=True, verbose_name='Вартість'),
        ),
    ]
