# Generated by Django 5.0.4 on 2024-06-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_1', '0004_course_date_price_course_description_course_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='images_courses', verbose_name='Картинка'),
        ),
    ]
